configs = [

######## THESIS

### NG ####
{"folder":"chapters/naminggame/normal",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"basic",
"tmax_type":"scaling_bigmax",
"params":["N","M",'W_inf_true'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/naminggame/VU",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"basic",
"tmax_type":"scaling_bigmax",
"params":["N","M_100",'W_inf_true','vu_type_basic'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/naminggame/wordchoice",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"basic",
"tmax_type":"scaling_bigmax",
"params":["N","M_1",'W_inf_true','wordchoice'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/naminggame/homonymy",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"basic",
"tmax_type":"scaling_bigmax",
"params":["N","M_1",'W_inf','accpol'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/naminggame/accpol",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"basic",
"tmax_type":"scaling_bigmax",
"params":["N","M_1",'W_inf_true','accpol'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},
###### ATC constraints ######

{"folder":"chapters/topicchoice/exploexplo",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_100","M_100",'W_inf','strat_type_exploexplo','vu_type_minimal'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/topicchoice/explobias",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_100","M_100",'W_inf','strat_type_explobiased'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/topicchoice/STW",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_100","M_100",'W_inf','strat_type_ST','threshold_param'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},


{"folder":"chapters/topicchoice/STN",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_few","M_100",'strat_type_ST','threshold_param'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/topicchoice/ST2",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_few","M_100",'strat_type_ST2','threshold_param'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/topicchoice/MCW",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_100","M_100",'W_inf','strat_type_MC','mincounts_param'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},


{"folder":"chapters/topicchoice/MCN",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_100","M_100",'W_inf','strat_type_MC','mincounts_param'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},

{"folder":"chapters/topicchoice/IGW",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_100","M_100",'W_inf','strat_type_infogain','temperature_param'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},


{"folder":"chapters/topicchoice/IGN",
"imports":["import naminggamesal as ngal"],
"nbiter":8,
"exec_type":"avakas",
"plt_settings":"classic",
"func_type":"ATC",
"tmax_type":"scaling_bigmax",
"params":["N_100","M_100",'W_inf','strat_type_infogain','temperature_param'],
"metrics_local":["Nlink","srtheo","N_d",'N_meanings','N_words','actual_successrate'],
"metrics_global":["conv_time","conv_time2","max_mem","max_N_d",'max_N_d_time','max_Nlink_time','tdiff_d','tdiff_w','tdiff_wd',],
},


]



if __name__ == '__main__':
	from experiment_manager.tools import metaexp_gen
	cfg_gen = metaexp_gen.ConfigGenerator()
	for c in configs:
		cfg_gen.auto_gen(**c)
