version: '3'

services:
  ngal:
    build: .
    container_name: notebooks_template
    command: sh -c "jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=$NOTEBOOKTOKEN"
    volumes:
      - .:/naminggamesal
    ports:
      - "$NOTEBOOKPORT:8888"
