set -e

strings=(
# "chapters/laps/previous"
# "chapters/laps/normal"
# "chapters/laps/lapsNT"
# "chapters/laps/lapsWT"
# # "chapters/laps/lapsNTimitation"
# # "chapters/laps/NMB_NT"
# "chapters/laps/lapsscaling"
# # "chapters/laps/lapsscaling_MB"
# "chapters/laps/coherenceNT"
# "chapters/laps/coherenceNTimitation"
# "chapters/laps/coherenceWT"
# "chapters/laps/coherencescaling"
# "chapters/laps/coherencescaling_MB"
"chapters/topicchoice/exploexplo"
"chapters/topicchoice/explobias"
"chapters/topicchoice/STW"
"chapters/topicchoice/STN"
"chapters/topicchoice/ST2"
"chapters/topicchoice/ST_HC"
"chapters/topicchoice/MCW"
"chapters/topicchoice/MCN"
"chapters/topicchoice/IGW"
"chapters/topicchoice/IGN"
"chapters/topicchoice/comparison"
"chapters/topicchoice/comparisonHC"
"chapters/naminggame/normal"
"chapters/naminggame/VU"
"chapters/naminggame/wordchoice"
"chapters/naminggame/homonymy"
"chapters/naminggame/accpol"
)

parallel --jobs 0 bash exec_one.sh ::: ${strings[@]}
